<?php

/**
 *
 * @author:  Baptiste BOUCHEREAU <baptiste.bouchereau@idci-consulting.fr>
 * @author:  Gabriel BONDAZ <gabriel.bondaz@idci-consulting.fr>
 * @license: GPL
 *
 */

namespace IDCI\Bundle\GenealogyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementRepository extends EntityRepository
{
   /**
    * extractQueryBuilder
    *
    * @param array $params
    * @return QueryBuilder
    */
   public function extractQueryBuilder($params)
   {
       $qb = $this->createQueryBuilder('e');

       if(isset($params['id'])) {
           $qb
               ->andWhere('e.id = :id')
               ->setParameter('id', $params['id'])
           ;
       }

       return $qb;
   }

   /**
    * extractQuery
    *
    * @param array $params
    * @return Query
    */
   public function extractQuery($params)
   {
       $qb = $this->extractQueryBuilder($params);

       return is_null($qb) ? $qb : $qb->getQuery();
   }

   /**
    * extract
    *
    * @param array $params
    * @return DoctrineCollection
    */
   public function extract($params)
   {
       $q = $this->extractQuery($params);

       return is_null($q) ? array() : $q->getResult();
   }
}
