<?php

namespace IDCI\Bundle\GenealogyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GenealogyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenealogyRepository extends EntityRepository
{
    
}
